#!/usr/bin/env bash
# ============================================================================
# Portable MySQL 5.7 data-directory bootstrap (runs ONCE).
# Creates local-db/data + local-db/my.cnf and sets up root credentials.
# The live server is then started by start-db.sh.
# ============================================================================
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DB_DIR="$ROOT/local-db"
DIST="$DB_DIR/mysql57"
DATA="$DB_DIR/data"
SOCK="$DB_DIR/mysql.sock"
PORT="${PORTABLE_DB_PORT:-3306}"
ROOT_PW="${PORTABLE_DB_ROOT_PASSWORD:-root}"
PY="$DB_DIR/.venv/bin/python"

[ -x "$DIST/mysqld" ] || { echo "[init-db] portable mysqld missing — run scripts/local/install-core.sh first"; exit 1; }
[ -x "$PY" ] || { echo "[init-db] db-admin venv missing — run scripts/local/install-core.sh first"; exit 1; }

export LD_LIBRARY_PATH="$DB_DIR/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
mkdir -p "$DB_DIR" "$DB_DIR/temp"

# my.cnf is (re)generated on every run so it always matches this machine.
cat >"$DB_DIR/my.cnf" <<EOF
# Madrasati portable MySQL database — generated by scripts/local/init-db.sh
[client]
default-character-set = utf8mb4
port = $PORT
socket = $SOCK

[mysqld]
basedir = $DIST
datadir = $DATA
socket = $SOCK
port = $PORT
bind-address = 127.0.0.1
pid-file = $DB_DIR/mysqld.pid
log-error = $DB_DIR/mysqld.log
tmpdir = $DB_DIR/temp
character-set-server = utf8mb4
collation-server = utf8mb4_unicode_ci
sql_mode = ""
default-storage-engine = InnoDB
innodb_file_per_table = 1
innodb_buffer_pool_size = ${PORTABLE_DB_BUFFER_POOL:-512M}
innodb_large_prefix = 1
innodb_file_format = Barracuda
max_allowed_packet = 64M
server-id = 1
disable-log-bin
explicit_defaults_for_timestamp = 1
log-bin-trust-function-creators = 1
max_connect_errors = 1000
EOF

if [ -d "$DATA/mysql" ]; then
	echo "[init-db] data directory already initialized: $DATA"
	exit 0
fi

echo "[init-db] initializing MySQL 5.7 data directory at $DATA ..."
"$DIST/mysqld" --defaults-file="$DB_DIR/my.cnf" --initialize-insecure

echo "[init-db] starting a temporary server to set credentials..."
"$DIST/mysqld" --defaults-file="$DB_DIR/my.cnf" --skip-networking &
TMP_PID=$!

ready=0
for _ in $(seq 1 60); do
	if [ -S "$SOCK" ] && "$PY" - "$SOCK" "$ROOT_PW" <<'PY' 2>/dev/null
import sys, pymysql
conn = pymysql.connect(unix_socket=sys.argv[1], user="root", password="")
conn.close()
PY
	then
		ready=1
		break
	fi
	sleep 0.5
done
[ "$ready" = "1" ] || { echo "[init-db] temporary server did not come up (see $DB_DIR/mysqld.log)"; tail -20 "$DB_DIR/mysqld.log" 2>/dev/null || true; exit 1; }

"$PY" - "$SOCK" "$ROOT_PW" <<'PY'
import sys, pymysql
sock, pw = sys.argv[1], sys.argv[2]
conn = pymysql.connect(unix_socket=sock, user="root", password="")
with conn.cursor() as c:
    c.execute("ALTER USER 'root'@'localhost' IDENTIFIED BY %s", (pw,))
    for host in ("127.0.0.1", "::1", "%"):
        c.execute(f"CREATE USER IF NOT EXISTS 'root'@'{host}' IDENTIFIED BY %s", (pw,))
        c.execute(f"GRANT ALL PRIVILEGES ON *.* TO 'root'@'{host}' WITH GRANT OPTION")
    c.execute("FLUSH PRIVILEGES")
conn.close()
PY

# graceful shutdown (SIGTERM = clean MySQL shutdown)
kill -TERM "$TMP_PID" 2>/dev/null || true
wait "$TMP_PID" 2>/dev/null || true
echo "[init-db] ✓ portable MySQL initialized (root password: ${ROOT_PW})"
